---
version: 0.2

env:
  variables:
    TEMPLATE_FILE: "main.yaml"
    PACKAGED_FILE: "packaged.yaml"
    S3_BUCKET: "mo-poc-s3"
    STACK_NAME: "my-poc-stack"
    REGION: "us-east-1"

phases:
  install:
    commands:
      - "echo Installing AWS CLI..."
      - "pip install --upgrade awscli"

  build:
    commands:
      - "echo Packaging nested templates..."
      - "aws cloudformation package --template-file $TEMPLATE_FILE --s3-bucket $S3_BUCKET --output-template-file $PACKAGED_FILE"

      # Debug: Check packaged template
      - "echo Contents of packaged template:"
      - "cat $PACKAGED_FILE"
      - "ls -l $PACKAGED_FILE"

      - "echo Creating change set..."
      - "export CHANGESET_NAME=changeset-$CODEBUILD_RESOLVED_SOURCE_VERSION"
      - "echo Change set name: $CHANGESET_NAME"

      # Create change set without using \ (no backslashes)
      - >
        if aws cloudformation describe-stacks --stack-name $STACK_NAME >/dev/null 2>&1; then
          echo "Stack exists. Creating UPDATE change set..."
          aws cloudformation create-change-set --stack-name $STACK_NAME --change-set-name $CHANGESET_NAME --template-body file://$PACKAGED_FILE --capabilities CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND --change-set-type UPDATE
        else
          echo "Stack does not exist. Creating CREATE change set..."
          aws cloudformation create-change-set --stack-name $STACK_NAME --change-set-name $CHANGESET_NAME --template-body file://$PACKAGED_FILE --capabilities CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND --change-set-type CREATE
        fi

      - "echo Waiting for change set creation to complete..."
      - >
        aws cloudformation wait change-set-create-complete --stack-name $STACK_NAME --change-set-name $CHANGESET_NAME || echo "No changes or error"

      - "echo Change set created: $CHANGESET_NAME"

artifacts:
  files:
    - packaged.yaml
