version: 0.2

env:
  variables:
    STACK_NAME: mo-wso2-dev
    S3_BUCKET: mo-poc-s3
    REGION: us-east-1

phases:
  install:
    commands:
      - echo "📦 Installing AWS CLI..."
      - pip install --upgrade awscli

  pre_build:
    commands:
      - echo "🔍 DEBUG: Checking environment variables..."
      - echo "STACK_NAME = $STACK_NAME"
      - echo "S3_BUCKET  = $S3_BUCKET"
      - echo "REGION     = $REGION"
      - echo "📁 Current working directory:"
      - pwd
      - echo "📂 Listing all files:"
      - ls -l

  build:
    commands:
      - echo "📦 Packaging CloudFormation templates..."
      - aws cloudformation package \
          --template-file main.yaml \
          --s3-bucket $S3_BUCKET \
          --output-template-file packaged.yaml \
          --region $REGION

      - echo "🚀 Running deploy.sh..."
      - chmod +x deploy.sh
      - ./deploy.sh

artifacts:
  files:
    - packaged.yaml
