version: 0.2

env:
  variables:
    TEMPLATE_FILE: "main.yaml"
    PACKAGED_FILE: "packaged.yaml"
    S3_BUCKET: "mo-poc-s3"
    STACK_NAME: "my-poc-stack"
    REGION: "us-east-1"

phases:
  install:
    commands:
      - echo "Installing AWS CLI..."
      - pip install --upgrade awscli

  build:
    commands:
      - echo "Packaging nested templates..."
      - aws cloudformation package --template-file $TEMPLATE_FILE --s3-bucket $S3_BUCKET --output-template-file $PACKAGED_FILE
      - echo "Running deployment script..."
      - chmod +x deploy.sh
      - ./deploy.sh

artifacts:
  files:
    - packaged.yaml
