version: 0.2

phases:
  install:
    commands:
      - echo "Installing AWS CLI..."
      - pip install --upgrade awscli
  build:
    commands:
      - echo "Running deploy.sh..."
      - chmod +x deploy.sh
      - ./deploy.sh

artifacts:
  files:
    - packaged.yaml
