version: 0.2

env:
  variables:
    REGION: "us-east-1"
    S3_BUCKET: "mo-poc-s3"
    STACK_NAME: "my-poc-stack"

phases:
  install:
    commands:
      - echo "Installing AWS CLI..."
      - pip install --upgrade awscli
  build:
    commands:
      - echo "Running deployment script..."
      - chmod +x deploy.sh
      - ./deploy.sh

artifacts:
  files:
    - packaged.yaml
