version: 0.2

env:
  variables:
    STACK_NAME: "my-poc-stack"
    TEMPLATE_FILE: "main.yaml"
    PACKAGED_FILE: "packaged.yaml"
    REGION: "us-east-1"

phases:
  install:
    commands:
      - echo "Installing AWS CLI..."
      - pip install --upgrade awscli

  build:
    commands:
      - echo "Packaging CloudFormation template..."
      - aws cloudformation package \
          --template-file $TEMPLATE_FILE \
          --s3-bucket mo-poc-s3 \
          --output-template-file $PACKAGED_FILE
      - echo "Deploy script execution..."
      - chmod +x ./deploy.sh
      - ./deploy.sh

artifacts:
  files:
    - packaged.yaml
