version: 0.2

env:
  variables:
    STACK_NAME: mo-wso2-dev
    S3_BUCKET: mo-poc-s3
    REGION: us-east-1

phases:
  install:
    commands:
      - echo "📦 Installing AWS CLI..."
      - pip install --upgrade awscli

  pre_build:
    commands:
      - echo "🔍 Verifying environment..."
      - echo "STACK_NAME = $STACK_NAME"
      - echo "S3_BUCKET  = $S3_BUCKET"
      - echo "REGION     = $REGION"
      - ls -l

  build:
    commands:
      - echo "🚀 Running deployment script..."
      - chmod +x deploy.sh
      - ./deploy.sh

artifacts:
  files:
    - packaged.yaml
