AWSTemplateFormatVersion: '2010-09-09'
Description: Child stack - creates an S3 bucket (POC).

Parameters:
  BucketNamePrefix:
    Type: String
    Description: Prefix for the bucket name (must be lowercase)

Resources:
  POCBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ['', [ !Ref BucketNamePrefix, '-', !Ref "AWS::StackName", '-', !Ref "AWS::Region" ]]
      
Outputs:
  BucketNameOutput:
    Description: Name of the created S3 bucket
    Value: !Ref POCBucket
