AWSTemplateFormatVersion: "2010-09-09"
Description: EC2 instance in private subnet

Parameters:
  Environment:
    Type: String
  VpcId:
    Type: String
  SubnetId:
    Type: String
  SecurityGroupId:
    Type: String
  IAMRoleName:
    Type: String

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: ami-0c94855ba95c71c99 # Example Amazon Linux 2
      SubnetId: !Ref SubnetId
      SecurityGroupIds:
        - !Ref SecurityGroupId
      IamInstanceProfile: !Ref IAMRoleName
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-ec2"
