AWSTemplateFormatVersion: "2010-09-09"
Description: EC2 Instance Stack

Parameters:
  Environment:
    Type: String
  VpcId:
    Type: String
  SecurityGroupId:
    Type: String
  IAMRoleName:
    Type: String
  SSHKeyName:
    Type: String

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0c94855ba95c71c99 # Example Amazon Linux 2 AMI
      InstanceType: t3.micro
      SubnetId: !Ref VpcId
      SecurityGroupIds:
        - !Ref SecurityGroupId
      KeyName: !Ref SSHKeyName
      IamInstanceProfile: !Ref IAMRoleName
