AWSTemplateFormatVersion: "2010-09-09"
Description: EC2 instance inside private subnet

Parameters:
  Environment:
    Type: String
  VpcId:
    Type: String
  SecurityGroupId:
    Type: String
  IAMRoleName:
    Type: String

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: ami-032562890a0e09052  # example, replace with your AMI
      SubnetId: !Ref VpcId
      SecurityGroupIds:
        - !Ref SecurityGroupId
      IamInstanceProfile: !Ref IAMRoleName
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-EC2"
