AWSTemplateFormatVersion: "2010-09-09"
Description: EC2 instance in private subnet

Parameters:
  Environment:
    Type: String
  VpcId:
    Type: String
  SubnetId:
    Type: String
  SecurityGroupId:
    Type: String
  InstanceRoleName:
    Type: String

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0aa7d40eeae50c9a9   # Ubuntu 22.04 in us-east-1 (update if region changes)
      InstanceType: t3.micro
      SubnetId: !Ref SubnetId
      IamInstanceProfile: !Ref InstanceRoleName
      SecurityGroupIds:
        - !Ref SecurityGroupId
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-ec2-instance"

Outputs:
  InstanceId:
    Value: !Ref EC2Instance
