AWSTemplateFormatVersion: '2010-09-09'
Description: Parent stack that launches the child nested stack (POC).

Parameters:
  BucketPrefix:
    Type: String
    Default: poc
    Description: Prefix to use for child S3 bucket (lowercase)

Resources:
  ChildStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: child-template.yaml  # aws cloudformation package will replace this with S3 URL
      Parameters:
        BucketNamePrefix: !Ref BucketPrefix

Outputs:
  ChildStackOutputBucketName:
    Description: Child stack S3 bucket name (propagated)
    Value: !GetAtt ChildStack.Outputs.BucketName
