AWSTemplateFormatVersion: '2010-09-09'
Description: Parent stack that launches the child nested stack (POC).

Parameters:
  BucketName:
    Type: String
    Description: Exact name for the child S3 bucket (must be lowercase)

Resources:
  ChildStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://s3.amazonaws.com/mo-poc-s3/child-template.yaml"
      Parameters:
        BucketName: !Ref BucketName

Outputs:
  ChildStackBucketName:
    Description: Child stack S3 bucket name (propagated)
    Value: !GetAtt ChildStack.Outputs.POCBucketName
