AWSTemplateFormatVersion: "2010-09-09"
Description: Main CF template for VPC, IAM, SecurityGroup, and EC2

Parameters:
  Environment:
    Type: String
    Default: "dev"

Resources:
  # IAM Role Stack
  IAMStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: iam.yaml
      Parameters:
        Environment: !Ref Environment

  # VPC Stack
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: vpc.yaml
      Parameters:
        Environment: !Ref Environment

  # Security Group Stack
  SecGrpStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: secgrp.yaml
      Parameters:
        Environment: !Ref Environment
        VpcId: !GetAtt VPCStack.Outputs.VpcId

  # EC2 Instance Stack
  EC2Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ec2.yaml
      Parameters:
        Environment: !Ref Environment
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        SecurityGroupId: !GetAtt SecGrpStack.Outputs.EC2SecurityGroupId
        IAMRoleName: !GetAtt IAMStack.Outputs.EC2RoleName
