AWSTemplateFormatVersion: "2010-09-09"
Description: Main template to deploy VPC, IAM, Security Group, and EC2 using nested stacks.

Parameters:
  Environment:
    Type: String
    Default: dev

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: vpc.yml
      Parameters:
        Environment: !Ref Environment

  IAMStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: iam.yaml
      Parameters:
        Environment: !Ref Environment

  SecGrpStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: secgrp.yaml
      Parameters:
        Environment: !Ref Environment
        VpcId: !GetAtt VPCStack.Outputs.VpcId

  EC2Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ec2.yaml
      Parameters:
        Environment: !Ref Environment
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        SecurityGroupId: !GetAtt SecGrpStack.Outputs.EC2SecurityGroupId
        InstanceRoleName: !GetAtt IAMStack.Outputs.InstanceRoleName

Outputs:
  VpcId:
    Description: VPC ID from nested stack
    Value: !GetAtt VPCStack.Outputs.VpcId

  EC2InstanceId:
    Description: EC2 instance ID from nested stack
    Value: !GetAtt EC2Stack.Outputs.InstanceId
