AWSTemplateFormatVersion: '2010-09-09'
Description: Main stack to create IAM, VPC, Security Group, and EC2 instance.

Parameters:
  Environment:
    Type: String
    Default: dev
  SSHKeyName:
    Type: String
    Default: my-key

Resources:
  IAMStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: iam.yaml
      Parameters:
        Environment: !Ref Environment

  VPCStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: IAMStack
    Properties:
      TemplateURL: vpc.yaml
      Parameters:
        Environment: !Ref Environment

  SecGrpStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCStack
    Properties:
      TemplateURL: secgrp.yaml
      Parameters:
        Environment: !Ref Environment
        VpcId: !GetAtt VPCStack.Outputs.VpcId

  EC2Stack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - IAMStack
      - VPCStack
      - SecGrpStack
    Properties:
      TemplateURL: ec2.yaml
      Parameters:
        Environment: !Ref Environment
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        SecurityGroupId: !GetAtt SecGrpStack.Outputs.EC2SecurityGroupId
        IAMRoleName: !GetAtt IAMStack.Outputs.EC2RoleName
        SSHKeyName: !Ref SSHKeyName
