AWSTemplateFormatVersion: "2010-09-09"
Description: Main stack that deploys VPC, IAM, Security Group, and EC2

Parameters:
  Environment:
    Type: String
    Default: dev

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: vpc.yaml
      Parameters:
        Environment: !Ref Environment

  IAMStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: iam.yaml
      Parameters:
        Environment: !Ref Environment

  SecurityGroupStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: secgrp.yaml
      Parameters:
        Environment: !Ref Environment
        VpcId: !GetAtt VPCStack.Outputs.VpcId

  EC2Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ec2.yaml
      Parameters:
        Environment: !Ref Environment
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        SubnetId: !GetAtt VPCStack.Outputs.PrivateSubnetId
        SecurityGroupId: !GetAtt SecurityGroupStack.Outputs.EC2SecurityGroupId
        InstanceRoleName: !GetAtt IAMStack.Outputs.InstanceRoleName
